# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aafaaa10dae1d4aed28fc701624b7d3a14079ab2128906ffb6a20f49484d5f0e5850aad2752e7a4ec43a31c0b38dfaa154a08dd23a70e73a196d985db311ff2

test:
  secret_key_base: c9797f1a3c69aef045fa9cc9952bdcf68057ef13a38a42e242eec543ea200bc309515f5a98b97978f2b931a62c20cc2ff4c959216888fb6c6be4e43e83d425a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
